openapi: 3.0.0
info:
  title: Jobs API
  contact: {}
  version: '1.0'
servers:
  - url: http://localhost:3000/api/v1
    variables: {}
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register
      operationId: Register
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/RegisterRequest'
                - example:
                    name: Ivan Kozak
                    email: ivankozak@gmail.com
                    password: '12345'
            example:
              name: Ivan Kozak
              email: ivankozak@gmail.com
              password: '12345'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      operationId: Login
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/LoginRequest'
                - example:
                    email: ivankozak@gmail.com
                    password: '12345'
            example:
              email: ivankozak@gmail.com
              password: '12345'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /jobs:
    get:
      tags:
        - Jobs
      summary: Get All Jobs
      operationId: GetAllJobs
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
        - Jobs
      summary: Create New Job
      operationId: CreateNewJob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/CreateNewJobRequest'
                - example:
                    company: epam
                    position: full-stack
                    createdBy: 6677ef22c7fe4af698e8bdbb
            example:
              company: epam
              position: full-stack
              createdBy: 6677ef22c7fe4af698e8bdbb
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /:
    get:
      tags:
        - Jobs
      summary: Get Single Job
      operationId: GetSingleJob
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /jobs/{id}:
    patch:
      tags:
        - Jobs
      summary: Update Job
      operationId: UpdateJob
      parameters: [id]
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/UpdateJobRequest'
                - example:
                    company: apple
            example:
              company: apple
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
    delete:
      tags:
        - Jobs
      summary: Delete Job
      operationId: DeleteJob
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    RegisterRequest:
      title: RegisterRequest
      required:
        - name
        - email
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: Ivan Kozak
        email: ivankozak@gmail.com
        password: '12345'
    LoginRequest:
      title: LoginRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: ivankozak@gmail.com
        password: '12345'
    CreateNewJobRequest:
      title: CreateNewJobRequest
      required:
        - company
        - position
        - createdBy
      type: object
      properties:
        company:
          type: string
        position:
          type: string
        createdBy:
          type: string
      example:
        company: epam
        position: full-stack
        createdBy: 6677ef22c7fe4af698e8bdbb
    UpdateJobRequest:
      title: UpdateJobRequest
      required:
        - company
      type: object
      properties:
        company:
          type: string
      example:
        company: apple
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Misc
    description: ''
  - name: Auth
    description: ''
  - name: Jobs
    description: ''